# render.yaml

- type: web_service
  name: vitalassist-api
  env: python
  branch: main
  buildCommand: pip install -r requirements.txt
  startCommand: gunicorn --bind 0.0.0.0:$PORT vitalassist_web_server:app
  plan: free

- type: static_site
  name: vitalassist-ui
  branch: main
  buildCommand: ""
  publishPath: .
  plan: free
